//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiferreteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_DETAIL
    {
        public decimal DETAIL_BILL_ID { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public decimal BILL_ID { get; set; }
        public decimal PRODUCT_QUANTITY { get; set; }
        public decimal PRODUCT_PRICE { get; set; }
        public decimal TOTAL { get; set; }
    }
}
