//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiferreteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public decimal CLIENT_ID { get; set; }
        public decimal USER_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public decimal CLIENT_PHONE { get; set; }
        public string CLIENT_ADDRESS { get; set; }
        public System.DateTime CLIENT_BIRTHDAY { get; set; }
    }
}
