//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiferreteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALER
    {
        public decimal DEALER_ID { get; set; }
        public decimal USER_ID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string RUBRO { get; set; }
    }
}
