//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiferreteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_GUIA_DESPACHO
    {
        public decimal DETALLE_GUIA_DESPACHO_ID { get; set; }
        public decimal GUIA_DESPACHO_ID { get; set; }
        public Nullable<decimal> BILL_DETAIL_ID { get; set; }
        public Nullable<decimal> TICKET_DETAIL_ID { get; set; }
    
        public virtual GUIA_DESPACHO GUIA_DESPACHO { get; set; }
    }
}
