//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiferreteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FERME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FERME()
        {
            this.GUIA_DESPACHO = new HashSet<GUIA_DESPACHO>();
        }
    
        public decimal FERRETERIA_ID { get; set; }
        public string FERRETERIA_RUT { get; set; }
        public string FERRETERIA_ADDRESS { get; set; }
        public decimal FERRETERIA_PHONE { get; set; }
        public string FERRETERIA_EMAIL { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string GIRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIA_DESPACHO> GUIA_DESPACHO { get; set; }
    }
}
