//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiferreteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIA_DESPACHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GUIA_DESPACHO()
        {
            this.DETAIL_GUIA_DESPACHO = new HashSet<DETAIL_GUIA_DESPACHO>();
        }
    
        public decimal GUIA_DESPACHO_ID { get; set; }
        public decimal FERRETERIA_ID { get; set; }
        public string DESPACHO_ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_GUIA_DESPACHO> DETAIL_GUIA_DESPACHO { get; set; }
        public virtual FERME FERME { get; set; }
    }
}
