//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiferreteria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILL> BILL { get; set; }
        public virtual DbSet<BILL_DETAIL> BILL_DETAIL { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<DEALER> DEALER { get; set; }
        public virtual DbSet<DETAIL_GUIA_DESPACHO> DETAIL_GUIA_DESPACHO { get; set; }
        public virtual DbSet<FERME> FERME { get; set; }
        public virtual DbSet<GUIA_DESPACHO> GUIA_DESPACHO { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<TICKET_DETAIL> TICKET_DETAIL { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<USER_TYPE> USER_TYPE { get; set; }
    }
}
