//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiferreteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public decimal PRODUCT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PRICE { get; set; }
        public decimal STOCK { get; set; }
        public decimal CRITICAL_STOCK { get; set; }
    }
}
